# Site settings
title: Gregory Knudsen
email: dev.artist15@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description. My website to tell you a little bit about myself, show
                you what I've been working on, and, probably most important,
                tell you what I've been learning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gregknudsen.me" # the base hostname & protocol for your site
twitter_username: greg99799
github_username:  greg99799

# Build settings
markdown: kramdown
